### ISSUE TITLE
Fix race conditions in tests

### ISSUE THREAD

**Issue by h2non** [vinxi/forward#2]

**Comment by groyoh** [comment]
Do we still have race conditions here?

**Comment by h2non** [comment]
Yes.

**Comment by groyoh** [comment]
I tried `go test -v -race` and no race condition was shown. Am i missing something here?

**Comment by h2non** [comment]
Which version of Go are you running?

**Comment by groyoh** [comment]
1.5.3

**Comment by h2non** [comment]
Have you tried with Go 1.6?

**Comment by groyoh** [comment]
Yes, still pass with 1.6

**Comment by groyoh** [comment]
Build works fine too https://travis-ci.org/vinxi/forward/builds/122129159

**Comment by groyoh** [comment]
Build worked fine for 1.6 https://travis-ci.org/vinxi/forward/jobs/122129160 but failed for 1.5 https://travis-ci.org/vinxi/forward/jobs/122129161

**Comment by h2non** [comment]
Thats the bad part of data races, it depends on random CPU scheduler cycles and are not always reproducible.

**Comment by h2non** [comment]
Moved to `vinxi/vinxi`.
